### Recuperar todas las compañias
GET http://localhost:1234/empresas

### Recuperar una compañia por id
GET http://localhost:1234/empresas/7a1cc21d-57a1-11ef-93be-803f5df2f1e3

### Crear una compañia con POST
POST http://localhost:1234/empresas
Content-Type: application/json

{
  "company_name": "Nueva",
  "constitution_date": "2024-08-07",
  "company_type": "Usuario final",
  "company_comments": "Otra muy buena compañía dentro del mercado de manufactura",
  "company_fav": false
}

### Borrar una compañia
DELETE http://localhost:1234/empresas/2d943e26-5695-11ef-93be-803f5df2f1e3

### Actualizar una compañia
PATCH http://localhost:1234/empresas/46d94c4f-568c-11ef-93be-803f5df2f1e3
Content-Type: application/json

{
  "constitution_date": "2024-01-07"
}